### ISSUE TITLE
[Feature Request] - Allow using rustls instead of native-tls

### ISSUE THREAD

**Issue by Stridsvagn69420** [veeso/suppaftp#19]
## Description

First of all: thank you continuing the rust-ftp crate! I looked for useful FTP crates for my package manager, that are also still maintained, and this was the only one that fits.
My small issue is that I want to use rustls (with the system CAs) when it comes to TLS. Reqwest allows me to do that, but it's obviously for HTTP and not FTP.
I'd appreciate if this gets implemented, though I don't really know how much effort it is to do so ^^'

### Changes

The following changes to the application are expected

- Add a new feature, e.g. rustls (and async-rustls), which allows using rustls instead of native-tls.

**Comment by veeso** [comment]
Hi,

Indeed it's something the effort is worth, but I need to check how to implement the stream.
I'll give it a try
