### ISSUE TITLE
[Feature Request] - Implement EPSV (Extended Passive Mode)

### ISSUE THREAD

**Issue by Brueggus** [veeso/suppaftp#28]
## Description

I'm trying to upload a file to an FTP server over a TLS-encrypted _IPv6_ connection. The upload fails with the following error message:
> Error: Invalid response: [425] 425 You cannot use PASV on IPv6 connections. Use EPSV instead.

The server is powered by Pure-FTPd.

PASV works for IPv4 only, therefore it's not possible to use passive mode over IPv6 at the moment.

More info: https://www.jscape.com/blog/what-is-the-ftp/s-epsv-command-and-when-do-you-use-it

### Changes

Suppaftp should use EPSV instead of PASV if required or requested by the server.

## Implementation

EPSV is defined in RFC2428: https://www.rfc-editor.org/rfc/rfc2428#section-3

**Comment by veeso** [comment]
That's definitely something that should be implemented. I'm in, but it will take some time 😅

**Comment by veeso** [comment]
Have you the possibility to test the feature importing suppaftp as a commit from this PR <https://github.com/veeso/suppaftp/pull/29>?

It should be enough to configure the client with

```rs
client.set_mode(Mode::ExtendedPassive);
```

**Comment by Brueggus** [comment]
Hey,
didn't you say it would take some time? ;)

I just tested your changes and the upload works fine now when `Mode::ExtendedPassive` is set.

Thanks a bunch! :)

**Comment by veeso** [comment]
Hahaha, I thought it would have been harder.

Before release though, I'm going to implement the entire RFC 2428 first
