### ISSUE TITLE
[QUESTION] - How to listen for server close events

### ISSUE THREAD

**Issue by BaLaLaLs** [veeso/suppaftp#32]
I am selecting an ftp client. I see that some nodejs ftp clients provide on functions. How can I know if my socket is alive in suppaftp.

**Comment by veeso** [comment]
Rust is not callback driven as Node, so probably there's no approach like that.
The ftpstream has an underlying `TcpStream`, which doesn't provide a `is_alive` function.

Probably the best way is just not caring about whether the socket is alive, but just handle errors in case a method won't work.

Another way, is using the FTP built-in command, which is designed probably for this reason, which is the `NOOP` command, so you should just call `stream.noop()` and on error consider the socket dead.

<https://docs.rs/suppaftp/latest/suppaftp/struct.FtpStream.html#method.noop>

**Comment by BaLaLaLs** [comment]
Thank you for answering my question.
