### ISSUE TITLE
Damaged uploaded image

### ISSUE THREAD

**Issue by nas-cod** [veeso/suppaftp#36]
## Description
I tried to upload the image, but I found that the uploaded image was damaged, what did I do wrong?

## Steps to reproduce

Steps to reproduce the bug you encountered
![图片](https://user-images.githubusercontent.com/79894501/221403846-81af71f7-9e27-4275-ac2b-52a60c8dab39.png)
## Environment

- OS: [Windows 11]
- Architecture [x86_64]
- Rust 1.67.1
- library 5.0.0
- Protocol used
- Remote server version and name: Ubuntu 22.04.2 LTS x86_64

## Additional information
There was no problem uploading the text, but the uploaded image was corrupted.

**Comment by veeso** [comment]
Hi,

I would try with `stream.transfer_type(FileType::Binary)`

**Comment by nas-cod** [comment]
> Hi,
> 
> I would try with `stream.transfer_type(FileType::Binary)`

There seems to be a new problem after I modified it.: 

Error Invalid response: [425] 425 You cannot use PASV on IPv6 connections. Use EPSV instead.

**Comment by nas-cod** [comment]
I've solved the problem and I think the README can work on it
```rust
use std::{fs};
use std::error::Error;
use std::fs::File;
use std::io::{Cursor, Read, Write};
use suppaftp::FtpStream;
use suppaftp::Mode::ExtendedPassive;
use suppaftp::types::FileType;


fn t()-> Result<(),Box<dyn Error>>{
    // Create a connection to an FTP server and authenticate to it.
    let mut ftp_stream = FtpStream::connect("1127.0.0.1:21")?;
    let _ = ftp_stream.login("account", "password")?;
    // Binary file transfer is supported
    ftp_stream.transfer_type(FileType::Binary)?;
    // Support for IPV6
    ftp_stream.set_mode(ExtendedPassive);
    // Switch ftp service directory
    let _ = ftp_stream.cwd("test_data")?;

    // put file.
    let mut file = fs::read("D:\\img.png")?;
    let x = file.as_slice();
    let mut cursor = Cursor::new(x);
    ftp_stream.put_file("greeting.png",& mut cursor)?;
    
    println!("Successfully wrote greeting.png");
    // Terminate the connection to the server.
    let _ = ftp_stream.quit();
    Ok(())
}

fn main() {
    match t() {
        Ok(_) => {}
        Err(e) => {
            println!("Error {}",e)
        }
    }
}
```
