### ISSUE TITLE
[BUG] - list method request failed BadResponse

### ISSUE THREAD

**Issue by llvvrui** [veeso/suppaftp#49]
### I use ftp command login.
![Snipaste_2023-07-14_10-30-19](https://github.com/veeso/suppaftp/assets/38856163/95ad01bb-b80c-4326-b9f5-8851178b0973)

**Comment by veeso** [comment]
From the screenshot, the issue is not clear. Please also provide what FTP server you're connected to.

**Comment by llvvrui** [comment]
Sorry,I can't ask FTP server version others,Only programming to test.

**Comment by llvvrui** [comment]
operating system is solaris 10！

**Comment by llvvrui** [comment]
I find this "For a very long time, the FTP server bundled with Solaris has been based on the WU-FTPd program. In Solaris 11, this has been changed to ProFTPd."

**Comment by llvvrui** [comment]
I use from_utf8_lossy method read u8 array buffer, maybe reason is buffer including characters that is not utf-8
![256156710-90c469d1-892e-4489-927d-9d5b27fe6d88](https://github.com/veeso/suppaftp/assets/38856163/5624dbb6-0d98-4d1a-8b89-906f820eb640)

**Comment by veeso** [comment]
This could be related to #50 maybe you could try with `opts("UTF8", Some("ON"))`
