### ISSUE TITLE
[BUG] - Ftp with TLS (native-tls) Not working

### ISSUE THREAD

**Issue by c60cb859** [veeso/suppaftp#54]
## Description

When copying the example from https://github.com/veeso/suppaftp#ftp-with-tls-native-tls the first unwrap errors with `status: NotLoggedIn`

## Steps to reproduce

1. `cargo new ftps_test`
2. `cd ftps_test`
3. `cargo add suppaftp -F native-tls`
4. Copy example to `main.rs`
5. `cargo run`

This gives me:
```
% cargo run
warning: unused import: `TlsStream`
 --> src/main.rs:1:42
  |
1 | use suppaftp::native_tls::{TlsConnector, TlsStream};
  |                                          ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `ftps_test` (bin "ftps_test") generated 1 warning (run `cargo fix --bin "ftps_test"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/ftps_test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedResponse(Response { status: NotLoggedIn, body: [53, 51, 48, 32, 78, 111, 116, 32, 108, 111, 103, 103, 101, 100, 32, 105, 110, 46, 13, 10] })', src/main.rs:12:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected behaviour

I would assume I could expect the unwraps and the assert to not give an error

## Environment

- OS: Arch Linux
- Architecture: x86
- Rust version: 1.70
- library version: 5.2.0
- Protocol used: FTPS
- Remote server version and name: test.rebex.net (not sure what they are running)

## Additional information

It could very well be me that does something wrong

**Comment by c60cb859** [comment]
I have now tried with the suppaftp-cli, getting the same `Not logged in` error

**Comment by c60cb859** [comment]
It might actually be the servers TLS configuration that is wrong

**Comment by veeso** [comment]
yeah, the rebex hasn't been working for a while

**Comment by c60cb859** [comment]
sorry for the bug :-D
