### ISSUE TITLE
[QUESTION] - Is there a plan to support sftp

### ISSUE THREAD

**Issue by WindSoilder** [veeso/suppaftp#65]
Hi, I'm looking for a ftp library, and find your crate is easily to use!  Thanks!

Since it doesn't mentioned about sftp, I think it doesn't support it for now, just wonder is there any plan to support it?

**Comment by veeso** [comment]
SFTP isn't related to FTP. Please, consider using the SSH2 library instead https://docs.rs/ssh2/latest/ssh2/
