### ISSUE TITLE
[BUG] - list parser: SyntaxError on name that starts with 2 numbers

### ISSUE THREAD

**Issue by clonejo** [veeso/suppaftp#69]
## Description

A file called `01 1234 foo.mp3` breaks the file listing parser.

Reducing the file name to one number makes the example below work.

## Steps to reproduce

```rust
let file: File = dbg!(File::from_str(
    "-r--r--r--    1 23        23         1234567 Jan 1  2000 01 1234 foo.mp3",
))
.ok()
.unwrap();
assert_eq!(file.name, "01 1234 foo.mp3");
```

`File::from_str()` returns `SyntaxError`.

## Environment

- OS: Arch
- Architecture x86_64
- Rust version rustc 1.76.0-beta.1 (0e09125c6 2023-12-21)
- library version: v5.3.0 a0537a274b5b51684952539643e7f69799544327
- Protocol used: FTP
- Remote server version and name: vsftpd

**Comment by veeso** [comment]
78aee867
