### ISSUE TITLE
[Feature Request] - Support MLST and MLSD

### ISSUE THREAD

**Issue by mousetail** [veeso/suppaftp#76]
## Description

The MLST and MLSD commands allow getting more detailed metadata about a file.

### Changes

Add something like this:

```rs
fn mlsd(pathname: Option<&str>) -> Vec<FileInfo>{

}

fn mlst(pathname: &str) -> FileInfo {

}

struct FileInfo {
    pathname: String,
    size: Option<usize>,
    created: Option<DateTime>,
    modified: Option<DateTime>,
    type: Option<TypeFact>,
    unique: Option<String>,
    perm: Option<String>,
    lang: Option<String>,
    media_type: Option<String>,
    charset: Option<String>,
    custom: HashMap<String, String>
}

enum TypeFact {
    File,
    Directory,
    CurrentDirectory,
    ParentDirectory
}
```

## Implementation

Should be fairly straightforward

**Comment by constituent** [comment]
I want these commands as well, but when I searched the doc and found nothing, my intuition was searching for some api to send raw command. After reading source code, I was surprised to find _ImplAsyncFtpStream.perform_ being private. 
Is there a reason that sending raw command not public? It forbids users to utilize lots of advanced features.

**Comment by veeso** [comment]
Reference <https://www.rfc-editor.org/rfc/rfc3659#page-23>

**Comment by veeso** [comment]
701071d6
