### ISSUE TITLE
[QUESTION] - Is there a way to use FTPS with `rustls`?

### ISSUE THREAD

**Issue by frederikhors** [veeso/suppaftp#86]
Is there a way to use FTPS with `rustls` instead of `default-tls`/`native-tls`?

**Comment by veeso** [comment]
you can choose the ssl backend you prefer

```toml
suppaftp = { version = "^6", features = ["rustls"] }
```

**Comment by frederikhors** [comment]
I'm referring to https://docs.rs/suppaftp/latest/suppaftp/#ftps-usage.

FTP"S".

Is it possible using `rustls` only?

**Comment by frederikhors** [comment]
I don't know how to use https://docs.rs/suppaftp/latest/suppaftp/struct.ImplFtpStream.html#method.into_secure with `rustls` feature only.

**Comment by frederikhors** [comment]
![image](https://github.com/veeso/suppaftp/assets/41120635/013876bf-fc5c-4161-9ecb-ac844e8cee13)
